name: Check version

on:
  pull_request:
    branches-ignore: [ "master" ]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check for version increment
        # Line 3 in CMakeLists.txt contains the project version
        run: |
          git switch ${{ github.event.pull_request.base.ref }}
          [[ $(git log -L3,3:CMakeLists.txt master..HEAD) ]]
